clear
close all
clc

N_B = 512*512;
resol_level = 4; %dimension of the regular grid

Hfolder = 'ImageDatabase/Human/';  %Folder where are located the artworks made by human artists
AIfolder ='ImageDatabase/AI/';  %Folder where are located the artworks generated by AI

Hfolder_RES = 'ImageDatabase/InUse_H/'; %Folder where the resized human images are saved
AIfolder_RES = 'ImageDatabase/InUse_AI/'; %Folder where the resized AI images are saved

delete(strcat(Hfolder_RES,'/*'));
delete(strcat(AIfolder_RES,'/*'));


dirNameH = strcat(Hfolder,'*jpg');
dirNameAI = strcat(AIfolder,'*jpeg');
 
resize_save(Hfolder,Hfolder_RES,dirNameH,N_B);
resize_save(AIfolder,AIfolder_RES,dirNameAI,N_B);

dirNameH = strcat(Hfolder_RES,'*jpg');
dirNameAI = strcat(AIfolder_RES,'*jpeg');

image_structH = dir(dirNameH);
image_structAI = dir(dirNameAI);
image_structH = natsortfiles(image_structH);
image_structAI = natsortfiles(image_structAI);

%Computes global aesthetic metrics for human artworks
[M_jH] = M_jCalculation(image_structH,Hfolder_RES,resol_level);
[M_KH] = M_KCalculation(image_structH,Hfolder_RES,resol_level);

%Computes global aesthetic metrics for AI artworks
[M_jAI] = M_jCalculation(image_structAI,AIfolder_RES,resol_level);
[M_KAI] = M_KCalculation(image_structAI,AIfolder_RES,resol_level);

x = linspace(1,size(image_structAI,1),size(image_structAI,1));




%Creates graphics for all the computed metrics.
figure
bar(x,[M_jAI;M_jH])

ylim([0.8 1])
title('AI vs. Human Jensen-Shannon order M_J')
xlabel('Painting label')
ylabel('M_J')
legend('AI','Human')

figure
bar(x,[M_KAI;M_KH])

ylim([0.2 0.5])
title('AI vs. Human NCD analysis M_{NCD}')
xlabel('Painting label')
ylabel('M_{NCD}') 

legend('AI','Human')


%Old graphics

% figure
% 
% plot(x,M_jH,'r:.','MarkerSize',20, LineStyle='none')
% grid on
% hold on
% plot(x,M_jAI,'b:.','MarkerSize',20, LineStyle='none')
% title('AI vs. Human Jensen-Shannon order M_J')
% xlabel('Painting label')
% ylabel('M_j') 
% 
% legend('Human','AI')
% hold off
% 
% 
% figure
% 
% plot(x,M_KH,'r:.','MarkerSize',20, LineStyle='none')
% grid on
% hold on
% plot(x,M_KAI,'b:.','MarkerSize',20, LineStyle='none')
% title('AI vs. Human NCD analysis M_K')
% xlabel('Painting label')
% ylabel('M_K') 
% 
% legend('Human','AI')
% hold off








